#!/usr/bin/perl
$references = 0;
while($line = <>) {
    $line =~ s/-\n//g;
    $line =~ s/  +/ /g;
    $line =~ s/[^\s\w -.;?!,öäåÖÄÅ]//g;
    $line =~ s/(\w)\?+/$1?/g;
    $line =~ s/\W+[\?!]+//g;
    if ($line =~ /^REFERENSER\n$/) {
        $references = 1;
    }
    if (!$references) {
        print $line;
    }
}
